# Generated by Django 6.0.7 on 2026-08-02 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_venta',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada')], max_length=20),
        ),
    ]
