# Generated by Django 6.0.7 on 2026-08-03 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_estado_venta'),
        ('ventas', '0002_venta_empleado_alter_venta_estado_venta'),
    ]

    operations = [
    ]
