# Generated by Django 6.0.7 on 2026-07-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('apellido_empleado', models.CharField(max_length=100)),
                ('cedula_empleado', models.CharField(max_length=10, unique=True)),
                ('correo_empleado', models.EmailField(max_length=254, unique=True)),
                ('telefono_empleado', models.CharField(max_length=10)),
                ('cargo_empleado', models.CharField(max_length=100)),
                ('salario_empleado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
