# Generated by Django 5.2.15 on 2026-08-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
